import Head from 'next/head';
import { Sidebar } from '@/components';


export default function Home() {
  return (
    <>
      <Head>
        <title>Twitter | Arshil </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-black h-screen w-screen' >
        <Sidebar />
      </div>
    </>
  );
}
